export default Object.freeze({
	HOME: 'Home',
	CALENDAR: 'Calendar',
	EVENT_EDIT: 'Edit Calendar Entry',
	DATE_EVENT_OVERVIEW: 'Calendar Entry Overview',
	TIMELINE: 'Timeline',
	ORGANIZATION_STACK_NAVIGATION: 'Organization',
	MEDICATION_STACK_NAVIGATION: 'Medication',
	MEDICATION_EDIT: 'Edit Medication',
	TEST: 'Test',
	DOCUMENTS_STACK_NAVIGATION: 'Document Navigation',
	FOLDER_MANAGEMENT: 'Document Management',
	WELCOME: 'Welcome',
	LOGIN: 'Login',
	REGISTER: 'Register',
	SETTINGS_STACK_NAVIGATION: 'Settings Navigation',
	SETTINGS: 'Settings',
});
